// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djtlirvmemmdmwldqpkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqdGxpcnZtZW1tZG13bGRxcGt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3Nzc0NDQsImV4cCI6MjA3MDM1MzQ0NH0.BbYVmWljlH0odBjYrFbkORv3nmGlinxGMNg_URZNRXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});